# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strobesbufs/messier/functions/slack.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='strobesbufs/messier/functions/slack.proto',
  package='strobesbufs.messier.function',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n)strobesbufs/messier/functions/slack.proto\x12\x1cstrobesbufs.messier.function\"-\n\x05Slack\x12\x13\n\x0bwebhook_url\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\tb\x06proto3'
)




_SLACK = _descriptor.Descriptor(
  name='Slack',
  full_name='strobesbufs.messier.function.Slack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='webhook_url', full_name='strobesbufs.messier.function.Slack.webhook_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='strobesbufs.messier.function.Slack.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=120,
)

DESCRIPTOR.message_types_by_name['Slack'] = _SLACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Slack = _reflection.GeneratedProtocolMessageType('Slack', (_message.Message,), {
  'DESCRIPTOR' : _SLACK,
  '__module__' : 'strobesbufs.messier.functions.slack_pb2'
  # @@protoc_insertion_point(class_scope:strobesbufs.messier.function.Slack)
  })
_sym_db.RegisterMessage(Slack)


# @@protoc_insertion_point(module_scope)
